### ISSUE TITLE
Callback described in the ReadMe does not seem to work anymore.

### ISSUE THREAD

**Issue by danieloc** [salty-pig/swapi-node#18]
Sorry about this now but whilst I was going through the ReadMe file I tried running this bit of code here that was described as an example usage:
// To get just 1 person
swapi.getPerson(1, function (err, result) {
    console.log(result);
});
Nothing would be printed out in the console. 
The promises work great - and I don't actually need to use callbacks, as I can just use the promises instead but I thought I would raise an issue about it.
I'm no expert so you'll have have to forgive me if I'm wrong haha!
Thanks :)

**Comment by lholmquist** [comment]
@danieloc  hmm, interesting,  thanks for reporting. 

just out of curiosity,  can you add the `err` to that console.log to see if there was an error

**Comment by lholmquist** [comment]
Lol, looks like i removed callbacks from the lib,  https://github.com/salty-pig/swapi-node/commit/d6e9fad279b5269bc7a290c7f927b7de69ba8b39 . 

i suppose i should remove that then from the readme.  Thanks for the reminder :)

**Comment by lholmquist** [comment]
fixed here:  fae8e1d3b26688945fb7fbc40f78e5e4f492d8e1

**Comment by danieloc** [comment]
Thanks @lholmquist
